name: akarosmi
version: 1.0.0+1
publish_to: none
description: Personal Library Management System.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.1
  intl: ^0.18.0
  image_picker: ^0.8.6+2
  flutter_slidable: ^2.0.0
  dio: ^5.0.0
  flutter_dotenv: ^5.0.2
  get_storage: ^2.0.3
  firebase_core: ^2.7.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env
  fonts:
    - family: karla
      fonts:
        - asset: assets\fonts\Karla\Karla-Bold.ttf
          weight: 700
        - asset: assets\fonts\Karla\Karla-Medium.ttf
          weight: 500
        - asset: assets\fonts\Karla\Karla-Regular.ttf
          weight: 400
        - asset: assets\fonts\Karla\Karla-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Karla\Karla-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Karla\Karla-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Karla\Karla-Light.ttf
          weight: 300
        - asset: assets\fonts\Karla\Karla-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets\fonts\Karla\Karla-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets\fonts\Karla\Karla-Italic.ttf
          weight: 400
          style: italic
        - asset: assets\fonts\Karla\Karla-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets\fonts\Karla\Karla-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets\fonts\Karla\Karla-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Karla\Karla-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: fjallaOne
      fonts:
        - asset: assets/fonts/Fjalla_One/FjallaOne-Regular.ttf
          weight: 400 
    

