name: akarosmi
version: 1.0.0+1
publish_to: none
description: Personal Library Management System.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.1
  intl: ^0.18.0
  image_picker: ^0.8.6+2
  flutter_slidable: ^2.0.0
  dio: ^5.0.0
  flutter_dotenv: ^5.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env
   
    

