name: akarosmi
version: 1.0.0+1
publish_to: none
description: Personal Library Management System.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.1
  date_time_field: ^0.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
   
    

