// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7fud_VB0ZRdAqnxI3wTg0Vdnip2DwwM',
    appId: '1:888933544920:web:ca092fed91501b13ac78ad',
    messagingSenderId: '888933544920',
    projectId: 'akarosmi-248e0',
    authDomain: 'akarosmi-248e0.firebaseapp.com',
    storageBucket: 'akarosmi-248e0.appspot.com',
    measurementId: 'G-CC3VD48K59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB-pgEGcAkIA96aEId5_0zRIgxeHfz2XE',
    appId: '1:888933544920:android:8f44726d0dc8921bac78ad',
    messagingSenderId: '888933544920',
    projectId: 'akarosmi-248e0',
    storageBucket: 'akarosmi-248e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxhqSomGF8OAFj63woaAqnCa4jccS-pQs',
    appId: '1:888933544920:ios:ebfdb85d0094c068ac78ad',
    messagingSenderId: '888933544920',
    projectId: 'akarosmi-248e0',
    storageBucket: 'akarosmi-248e0.appspot.com',
    iosClientId: '888933544920-hug3fso12misl58cdgpb3ohp24rhfut7.apps.googleusercontent.com',
    iosBundleId: 'com.kurm.akarosmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxhqSomGF8OAFj63woaAqnCa4jccS-pQs',
    appId: '1:888933544920:ios:ebfdb85d0094c068ac78ad',
    messagingSenderId: '888933544920',
    projectId: 'akarosmi-248e0',
    storageBucket: 'akarosmi-248e0.appspot.com',
    iosClientId: '888933544920-hug3fso12misl58cdgpb3ohp24rhfut7.apps.googleusercontent.com',
    iosBundleId: 'com.kurm.akarosmi',
  );
}
